### ISSUE TITLE
[FEATURE] - Take advantage of [ValidateNotNullorEmpty()]

### ISSUE THREAD

**Issue by jdhitsolutions** [powershellpr0mpt/PSP-Inventory#11]
Something you might want to consider is using the [ValidateNotNullorEmpty()] parameter attribute throughout your commands, especially on the Computername parameter. I like that you are using parameter binding. But this means that the user may unintentionally pass a value that is empty or blank.  Depending on the command they may not get a result.

```powershell
PS S:\> $c | get-sysinfo
PS S:\>
```
In this example $c was created earlier by some other process which may or may not have correctly defined a computername value. Without parameter validation nothing happens from the user's perspective. But if you add the parameter validation, then the command will throw an exception.

**Comment by powershellpr0mpt** [comment]
Great tip, completely forgot about that one!
