### ISSUE TITLE
[FEATURE] - Improve CIM Performance by selecting properties

### ISSUE THREAD

**Issue by jdhitsolutions** [powershellpr0mpt/PSP-Inventory#12]
Many of your commands rely on getting values from remote computers using `Get-Ciminstance`. Even better, your commands let you manage multiple computers. You can improve performance by telling `Get-Ciminstance` to only get the properties you need. This will speed up each command and overall make your command better performing.

For example, in `Get-OSInfo` you have a command like this.

```powershell
(Get-CimInstance -Query 'SELECT * FROM SoftwareLicensingService' -ComputerName $Computer).OA3xOriginalProductKey
```
If I manually run that command on a remote computer it takes about 3 seconds. But, if I change it to this:

```powershell
(Get-CimInstance -Query 'SELECT OA3xOriginalProductKey FROM SoftwareLicensingService' -ComputerName $Computer).OA3xOriginalProductKey
```
It took almost no time at all. Well under a second. I ran your command as written against a single physical computer and it took 27 seconds. I then made a local version of the function that used selected properties.

```powershell
$TimeZone = Get-CimInstance -ClassName Win32_TimeZone -ComputerName $Computer -property Caption -ErrorAction Stop
                $OS = Get-CimInstance -ClassName Win32_OperatingSystem -ComputerName $Computer -property Caption,Version,
                ServicePackMajorVersion,ServicePackMinorVersion,LastBootupTime,OSArchitecture
                $ProductKey = (Get-CimInstance -Query 'SELECT OA3xOriginalProductKey FROM SoftwareLicensingService' -ComputerName $Computer).OA3xOriginalProductKey
                $PageFile = Get-CimInstance -ClassName Win32_PageFile -ComputerName $Computer -Property name,filesize
```

This version only took 16 seconds. Be selective and it will really pay off.

**Comment by powershellpr0mpt** [comment]
I always tell people to filter left and only request what you need... but never actually thought about it properly with these queries...

***head desk***

This definitely needs to be sorted quickly.
Low hanging fruit

**Comment by jdhitsolutions** [comment]
This is easy to overlook. You get a result and it there really isn't a problem. But you, like many people, are probably testing with a few remote machines, most likely local VMs which respond quickly. But when you start thinking about someone running this against 500 servers, every little bit of savings begins to add up and the performance gains are noticeable. 

All that said, the other thing to consider is who might use this and how. If the assumption is that this will run as a scheduledjob to periodically populate a database or build an HTML report then the extra time is probably irrelevant. But for interactive, "I need to see this now", use, that's another story.

**Comment by powershellpr0mpt** [comment]
I tested it with local machines yeah, but also immediately implementing on an environment where I need to query 200 machines, so any performance gain that's available is definitely great.
Especially when it's as "simple" as this!
