### ISSUE TITLE
[FEATURE] - Improve CIM Performance with CimSessions

### ISSUE THREAD

**Issue by jdhitsolutions** [powershellpr0mpt/PSP-Inventory#13]
As you continue to revise your functions, another area where you will see significant performance is by using CIMSessions. This is especially true in functions where you are making multiple `Get-CimInstance` calls. I'd first suggest adding a parameter set for a cimsession. Then in your code, if the user passes a computername, create a temporary cimsession and use that. Remove it at the end.

Here is a refactored version of `Get-OSInfo` that uses parameter sets and CIMSessions.

```powershell
#move data collection to a private function
function _GetOSInfo {
    [cmdletbinding()]
    Param(
        [Microsoft.Management.Infrastructure.CimSession]$Cimsession
    )

    Write-Verbose "Gathering OS information from $($Cimsession.computername.toUpper())"
    $TimeZone = Get-CimInstance -ClassName Win32_TimeZone -cimsession $cimsession -property Caption -ErrorAction Stop
    $OS = Get-CimInstance -ClassName Win32_OperatingSystem -cimsession $cimsession -property Caption, Version,
    ServicePackMajorVersion, ServicePackMinorVersion, LastBootupTime, OSArchitecture
    $ProductKey = (Get-CimInstance -Query 'SELECT OA3xOriginalProductKey FROM SoftwareLicensingService' -cimsession $cimsession).OA3xOriginalProductKey
    $PageFile = Get-CimInstance -ClassName Win32_PageFile -cimsession $cimsession -Property name, filesize

    $OperatingSystem = [PSCustomObject]@{
        ComputerName   = $Cimsession.computername.toUpper()
        Caption        = $OS.Caption
        Version        = $OS.Version
        ServicePack    = ("{0}.{1}" -f $OS.ServicePackMajorVersion, $OS.ServicePackMinorVersion)
        ProductKey     = $ProductKey
        LastReboot     = $OS.LastBootUpTime
        OSArchitecture = $OS.OSArchitecture
        TimeZone       = $TimeZone.Caption
        PageFile       = $PageFile.Name
        PageFileSizeGB = ([math]::round(($PageFile.FileSize / 1GB), 0))
        InventoryDate  = (Get-Date)
    }
    $OperatingSystem.PSTypeNames.Insert(0, 'PSP.Inventory.OperatingSystemInfo')
    $OperatingSystem

}

function Get-JHOSInfo {

    [OutputType('PSP.Inventory.OperatingSystemInfo')]
    [Cmdletbinding(DefaultParameterSetName = "computer")]
    param(
        [Parameter(Position = 0, ValueFromPipeline, ValueFromPipelineByPropertyName, ParameterSetName = "computer")]
        [ValidateNotNullorEmpty()]
        [String[]]$ComputerName = $env:COMPUTERNAME,
        [Parameter(ParameterSetName = "computer")]
        [pscredential]$Credential,
        [Parameter(Position = 0, ValueFromPipeline, ParameterSetName = "session")]
        [Microsoft.Management.Infrastructure.CimSession[]]$Cimsession
    )
    begin {
        #not used
    }
    process {

        if ($pscmdlet.ParameterSetName -eq 'computer') {

            #initialize an array to hold sessions
            $Cimsession = @()
            #define a hashtable of parametes to splat to New-Cimsession
            $newParams = @{
                ErrorAction  = "Stop"
                Computername = ""
            }

            if ($credential.username) {
                $newParams.add("Credential", $Credential)
            }
            foreach ($Computer in $ComputerName) {
`               $newParams.computername = $computer
                Try {
                    $cimsession += New-CimSession @newParams
                }
                catch [Microsoft.Management.Infrastructure.CimException] {
                    Write-Warning "'$($Computer.toUpper())' does not have CIM access, reverting to DCOM instead"
                    $CimOptions = New-CimSessionOption -Protocol DCOM
                    $newParams.add("SessionOption", $CimOptions) | Out-Null
                    try {
                        $CimSession += New-CimSession @newParams
                    }
                    catch {
                        Write-Warning "'$($Computer.toUpper())' cannot be reached. $($_.exception.message)"
                    }
                    Finally {
                        #remove Cimoptions from PSBoundParameters
                        $newParams.remove("SessionOption") | Out-Null
                    }
                }
                Catch {
                    Write-Warning "'$($Computer.toUpper())' cannot be reached. $($_.exception.message)"
                }

            } #foreach computer
        } #if computername parameter set

        #get the data through each session
        foreach ($session in $cimsession) {
            _getOSInfo -Cimsession $session
        }

    } #process

    End {
        #remove cim sessions created for computers
        if ($pscmdlet.ParameterSetName -eq "computer" -AND $Cimsession.count -gt 0) {
            Remove-Cimsession $cimsession
        }

    } #end

} #close function
```
Notice that I moved the working code to a private function. You were having to repeat yourself before if you fell back to a DCOM connection.  

When I run this function using a computername, it takes about 5 seconds now. If I pass it an existing CIMSession it takes just under 3 seconds. Your current version for the same computer takes almost 30 seconds because of all the CIM overhead.

**Comment by powershellpr0mpt** [comment]
Looking at the code change, let me see if I got this right:

1. If I have a CIM session already available, I can use that with the new public function
2. If I don't have a CIM session available, it will create all the sessions required [for every computer] before actually querying them all. This would be faster than the current setup when providing a large set of computers to query, but would sequentially create sessions for all machines before querying them sequentially.

The reason I'm asking is because I'm also looking into using the PoshRSJob module with this module, where I divide my workload over multiple runspaces.
Now by the looks of it, there's definitely speed to be gained, but I'm wondering how much compared to running it through PoshRSJobs.

Definitely something for me to look into as the speed gain is just immense based on your data.
It also tackles another issue I've been having in my head, the repeating of work when falling back to DCOM never felt "right", but I didn't know another way around it.

**Comment by jdhitsolutions** [comment]
Personally, I don't think you should make incorporate PoshRSJob into your commands. Write your commands so that they perform the best that they can be interactively. If someone wants to use your commands with PoshRSJob, or even if you do, then they (you) can write control scripts to set all that up. But it has nothing to do with this module. Again, don't code yourself into a corner.

And you are right about the cimsessions. My sample code creates $cimsession from the computername. That way your code is very simple.  As for the DCOM stuff, if it were me, I wouldn't try to handle that for the user. If they have a legacy server, they can create their own CIMSession and since you are updating it to accept cimsessions, they can then use  your command. Adding the DCOM code is making your function more complicated than it really needs to be.  Personally, I'd get rid of it and assume WSMAN.

**Comment by powershellpr0mpt** [comment]
Problem I have at the moment is that I have a customer for which 75% of the servers don't have WSMAN properly configured and I can't get the data I need.
So basically added the functionality for myself. 

Even though I really really would prefer using WSMAN, the collection of actual data is key here.

**Comment by jdhitsolutions** [comment]
That's ok. Write your function to accept computernames or CIMSessions. Then when you need to use it create a controller script to run through your customer list of servers, generating sessions as needed, then feed those sessions to your command. The whole point of your function is that it should be re-usable and flexible. Create separate control vehicles to use the functions.
