### ISSUE TITLE
[BUG] - Get-PspSysInfo reporting physical/virtual incorrect

### ISSUE THREAD

**Issue by powershellpr0mpt** [powershellpr0mpt/PSP-Inventory#24]
**Describe the bug**
incorrect reports on `Get-PspSysInfo`
Virtual machines are getting reported as physicals

**To Reproduce**
`Get-PspSysInfo` on a Hyper-V VM

**Expected behavior**
Hyper-V VM should report as virtual machine, not physical

**Comment by jdhitsolutions** [comment]
Looks like the manufacturer is "Microsoft Corporation". I'd leave HyperV in your regex and add Microsoft.
