### ISSUE TITLE
[FEATURE] - Better error handling for Get-PspServerRole

### ISSUE THREAD

**Issue by jdhitsolutions** [powershellpr0mpt/PSP-Inventory#25]
*Your* expectation is that Get-PspServerRole will be used to query a server. But someone else might intentionally, or unintentionally query a desktop or some other system without the Win32_ServerFeature namespace. Right now the user gets an ugly error. It would be nicer to more gracefully handle this error and gently explain the remote computer needs to be a Windows server. Try/Catch is probably the way to go.

**Comment by powershellpr0mpt** [comment]
You're absolutely right, I'll try and add error handing to increase the user experience.
As "developer" you just test it against what you assume is the "normal" expected behaviour, but this is something that should simply be implemented.
Thanks for the catch!
