### ISSUE TITLE
[FEATURE] - InventoryDate should be a [datetime]

### ISSUE THREAD

**Issue by jdhitsolutions** [powershellpr0mpt/PSP-Inventory#9]
I suggest that anything you are reporting as a datetime should be treated as a [datetime] object. Right now, you are defining a date string for things like InventoryDate. This is an example of coding yourself into a corner. By formatting the date, you are imposing a structure that the user might not want or anticipate. For example, when I see this output

```powershell
...
PartitionNumber    : 1
IsPrimaryPartition : True
IsBootPartition    : False
InventoryDate      : 01-03-2019 08:46:08
```
I immediately interpret that as January 3, 2019 because I am in the US. If you left InventoryDate as the result of `Get-Date` then I would see a result that makes sense to me and you would see a format that makes sense to you. This also makes it possible to accurately sort on this property.

If you truly want the date to be formatted a specific way, then you can create a format.ps1xml file and define it there in a scriptblock.

**Comment by powershellpr0mpt** [comment]
You are correct, I thought that it would remain a datetime object, but formatted.
I will have to create format.ps1xml files, also to provide default properties in table format as it's nicer on the  eyes.

**Comment by jdhitsolutions** [comment]
You might try using the `New-PSFormatXML` command in my PSScriptTools module to generate the format.ps1xml file.
